config/routes.rb
Ratebeer::Application.routes.draw do
  resources :memberships

  resources :beer_clubs

  root 'breweries#index'

  resources :beers
  resources :breweries

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :memberships do
    get 'confirm', on: :member
  end

  resources :ratings, :only => [:index, :new, :create, :destroy]

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'

  get 'brewerylist', to:'breweries#list'
  
  resources :places, :only => [:index, :show]
  post 'places', to: 'places#search'

  resources :users
  get 'signup', to: 'users#new'

  resources :sessions, :only => [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships

  def to_s
    "#{name}, #{city}"
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :ensure_that_signed_in, :except => [:index, :show]
  before_action :ensure_that_admin, :only => [:destroy]

  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]

  # GET /beer_clubs
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club

    @confirmed_users = User.joins(memberships: :beer_club).where('memberships.confirmed' => true, 'beer_clubs.id' => @beer_club.id)
    
    if current_user and not Membership.find_by_user_id_and_beer_club_id_and_confirmed(current_user.id, @beer_club.id, true).nil?
      @current_user_is_a_member = true
    else
      @current_user_is_a_member = false
    end

    if @current_user_is_a_member
      @pending_memberships = Membership.where(beer_club: @beer_club, confirmed: false).all
    end
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  def create
    @beer_club = BeerClub.new(beer_club_params)   

    if @beer_club.save

      # Make the creating user a member of the bclub
      @membership = Membership.new(beer_club: @beer_club, user: current_user, confirmed: true)

      if @membership.save
        redirect_to @beer_club, notice: 'Beer club was successfully created.'
      else
        render action: 'new'
      end
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /beer_clubs/1
  def update
    if @beer_club.update(beer_club_params)
      redirect_to @beer_club, notice: 'Beer club was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /beer_clubs/1
  def destroy
    @beer_club.destroy
    redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.number_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<h1>Listing beer clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= beer_club.name %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td><%= link_to 'Show', beer_club, class:'btn btn-xs btn-primary' %></td>
        <td><%= link_to 'Edit', edit_beer_club_path(beer_club), class:'btn btn-xs btn-primary' %></td>
        <td><%= link_to 'Destroy', beer_club, method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: 'Are you sure?' } if current_user and current_user.admin %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer club', new_beer_club_path, class:'btn btn-xs btn-primary' %>

app/views/beer_clubs/new.html.erb
<h1>New beer club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<h1><%= @beer_club.to_s %></h1>

<p>Founded <%= @beer_club.founded %></p>

<% unless @beer_club.users.count == 0 %>
  <p>
    <strong>Members:</strong>
    <ul>
      <% @confirmed_users.each do |m| %>
        <li><%= link_to m.username, user_path(m) %></li>
      <% end %>
    </ul>
  </p>
<% end %>

<% unless @pending_memberships.nil? or @pending_memberships.count == 0 %>
  <p>
    <strong>Outstanding applications:</strong>
    <ul>
      <% @pending_memberships.each do |m| %>
        <li><%= m.user.username %> <%= link_to 'confirm', confirm_membership_path(m.id), class:'btn btn-xs btn-primary' %></li>
      <% end %>
    </ul>
  </p>
<% end %>

<% if current_user and not @current_user_is_a_member %>
  <%= form_for(@membership) do |f| %>
    <%= f.hidden_field :beer_club_id %>
    <%= f.submit class:'btn btn-primary', value:'Join the club' %>
  <% end %>
<% end %>

<p><%= link_to 'Edit', edit_beer_club_path(@beer_club), class: 'btn btn-xs btn-primary' %></p>
<p><%= link_to 'Back', beer_clubs_path %></p>