config/routes.rb
Ratebeer::Application.routes.draw do
  resources :memberships

  resources :beer_clubs

  root 'breweries#index'

  resources :beers
  resources :breweries

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :memberships do
    get 'confirm', on: :member
  end

  resources :ratings, :only => [:index, :new, :create, :destroy]

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'

  get 'brewerylist', to:'breweries#list'
  
  resources :places, :only => [:index, :show]
  post 'places', to: 'places#search'

  resources :users
  get 'signup', to: 'users#new'

  resources :sessions, :only => [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  include AverageRating

  has_secure_password

  validates :username, uniqueness: true, length: { 
    minimum: 3, 
    maximum: 15 
  }
  validates :password, format: {
    with: /\A(.*\d+.*[A-Z]+.*)|(.*[A-Z]+.*\d+.*)\z/,
    message: "should include at least one capital letter and at least one digit"
  }
  validates :password, length: {
    minimum: 4
  }

  has_many :ratings, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships
  has_many :beers, through: :ratings

  def self.top(n)
    sorted_by_rating_in_desc_order = User.all.sort_by{ |u| - (u.ratings.count||0) }
    sorted_by_rating_in_desc_order[0...n]
  end

  def favorite_beer
    return nil if ratings.empty?
    ratings.order(score: :desc).limit(1).first.beer
  end

  def to_s
    username
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.includes(:beers, :ratings).all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    if user_params.username.nil? and @user == current_user and @user.update(user_params)
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.'
      else
        render action: 'edit'
      end
    else
      redirect_to :back
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy if @user == current_user

    session.clear
    
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      @confirmed_clubs = BeerClub.joins(users: :memberships).where('memberships.confirmed' => true, 'users.id' => @user)
      @pending_clubs = BeerClub.joins(users: :memberships).where('memberships.confirmed' => false, 'users.id' => @user)
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-hover">
  <thead>
    <th> </th>
    <th> rated beers </th>
    <th> total ratings </th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<p>has made <%= pluralize(@user.ratings.count, 'rating') %> 
<% if (@user.ratings.count > 0) %>
  (average score <%= round @user.average_rating %>)
<% end %></p>

<% unless @user.ratings.count == 0 %>
<h2>ratings</h2>
<ul>
  <% @user.ratings.each do |r| %>
    <li>
      <%= r.beer.name %> <%= r.score %> 
      <% if @user == current_user %>
       <%= link_to 'delete', rating_path(r), method: :delete %>
      <% end %>
    </li>
  <% end %>
</ul>
<% end %>

<% unless @user.beer_clubs.count == 0 %>
 <p>
   member of 
   <% @confirmed_clubs.each do |c| %>
     <%= link_to c.to_s, beer_club_path(c) %>
   <% end %>
 </p>

 <p>
   memberships waiting approval:
   <% @pending_clubs.each do |c| %>
     <%= link_to c.to_s, beer_club_path(c) %>
   <% end %>
 </p>
<% end %>

<% if @user == current_user %>
  <%= link_to 'Edit', edit_user_path(@user), class:'btn btn-xs btn-primary' %>
  <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
<% end %>
<p><%= link_to 'Back', users_path %></p>