config/routes.rb
Ratebeer::Application.routes.draw do
  resources :memberships

  resources :beer_clubs

  root 'breweries#index'

  resources :beers
  resources :breweries

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :memberships do
    get 'confirm', on: :member
  end

  resources :ratings, :only => [:index, :new, :create, :destroy]

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'

  get 'brewerylist', to:'breweries#list'
  
  resources :places, :only => [:index, :show]
  post 'places', to: 'places#search'

  resources :users
  get 'signup', to: 'users#new'

  resources :sessions, :only => [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include AverageRating

  def year_cannot_be_in_the_future
    if year.present? && year > Time.now.year
      errors.add(:year, "can't be in the future")
    end
  end

  has_many :beers, :dependent => :destroy
  has_many :ratings, :through => :beers

  validates :name, presence: true

  validate :year_cannot_be_in_the_future
  
  validates :year, numericality: {
    greater_than_or_equal_to: 1042,
    only_integer: true
  }

  scope :active, -> { where active:true }
  scope :retired, -> { where active:[nil,false] }
  
  def self.top(n)
    sorted_by_rating_in_desc_order = Brewery.all.sort_by{ |b| - (b.average_rating||0) }
    sorted_by_rating_in_desc_order[0...n]
  end

  def to_s
    name
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :ensure_that_signed_in, :except => [:index, :show]
  before_action :ensure_that_admin, :only => [:destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    order = params[:order] || 'name'

    case order
      when 'name' 
        @active_breweries = Brewery.active.order('breweries.name')
        @retired_breweries = Brewery.retired.order('breweries.name')
      when 'year'
        @active_breweries = Brewery.active.order('breweries.name')  
        @retired_breweries = Brewery.retired.order('breweries.year')
    end    
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
    @brewery = Brewery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brewery }
    end
  end

  def list
  end

  # GET /breweries/new
  # GET /breweries/new.json
  def new
    @brewery = Brewery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brewery }
    end
  end

  # GET /breweries/1/edit
  def edit
    @brewery = Brewery.find(params[:id])
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"
    redirect_to :back, notice:"brewery activity status changed to #{new_status}"
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render json: @brewery, status: :created, location: @brewery }
      else
        format.html { render action: "new" }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /breweries/1
  # PUT /breweries/1.json
  def update
    @brewery = Brewery.find(params[:id])

    respond_to do |format|
      if @brewery.update_attributes(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery = Brewery.find(params[:id])
    @brewery.destroy

    respond_to do |format|
      format.html { redirect_to breweries_url }
      format.json { head :no_content }
    end
  end

  private

  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Year</th>
  </tr>
  </thead>

  <tbody>
  <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
	<td><%= link_to 'Edit', edit_brewery_path(brewery), class:'btn btn-xs btn-primary' %></td>
	<td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-xs btn-danger' if current_user.admin unless current_user.nil? %></td>
        <td></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Listing breweries</h1>
<h2>Active breweries</h2>
<p>Number of active breweries: <%= @active_breweries.count %> </p>
<%= render 'list', breweries: @active_breweries %>

<h2>Retired breweries</h2>
<p>Number of retired breweries: <%= @retired_breweries.count %> </p>
<%= render 'list', breweries: @retired_breweries %>

<p><%= link_to 'New Brewery', new_brewery_path, class:'btn btn-xs btn-primary' %></p>
<p><%= link_to 'List all beers', beers_path %></p>

app/views/breweries/list.html.erb
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.10/angular.min.js"></script>
<script>
    function BreweriesController($scope, $http) {
        $http.get('breweries.json').success( function(data, status, headers, config) {
            $scope.breweries = data;
        });

        $scope.order = 'name';

        $scope.orderBy = function (criteria){
            $scope.order = criteria;
        }
    }
</script>

<h2>Breweries</h2>

<div ng-app ng-controller="BreweriesController">
  <table class="table table-hover">
    <thead>
      <th><a ng-click="orderBy('name')">Name</a></th>
      <th><a ng-click="orderBy('year')">Founded</a></th>
      <th><a ng-click="orderBy('beers.count')">Number of beers</a></th>
    </thead>
    <tr ng-repeat="brewery in breweries | orderBy:order ">
      <td>
	{{brewery.name}}
      </td>
      <td>
	{{brewery.year}}
      </td>
      <td>
	{{brewery.beers.count}}
      </td>
    </tr>
  </table>
</div>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<h2>
  <%= @brewery.name %>
  <% if not @brewery.active %>
    <span class="label label-info">retired</span>
  <% end %>
</h2>
<emp>Established at <%= @brewery.year %></emp>

<p>
  <strong>Beers:</strong>
  <%= @brewery.beers.count %>
</p>
<p>
  <% @brewery.beers.each do |b| %>
  <%= link_to b.name, b %>
  <% end %>
</p>
<p>
  <% if @brewery.ratings.empty? %>
  There is no ratings for beers of this brewery.
  <% else %>
  <%= pluralize(@brewery.ratings.count, 'rating') %>, average <%= round @brewery.average_rating %>
  <% end %>
</p>

<p><%= link_to 'Toggle activity', toggle_activity_brewery_path(@brewery.id), method: :post, class: 'btn btn-primary' %>
<%= link_to 'Edit', edit_brewery_path(@brewery), class: 'btn btn-primary' %></p>
<p><%= link_to 'Back', breweries_path %></p>